### ISSUE TITLE
make  the join us image clickable

### ISSUE THREAD

**Issue by SCALagos** [SCALagos/SCALagos#11]
make the banner clickable to open  our Google form  -- https://forms.gle/5WgpkNx2wHEkBi9o7

**Comment by SCALagos** [comment]
issue still pending

**Comment by AdaOkonkwoTech** [comment]
> issue still pending

Am interested in fixing this if it is still open

**Comment by hossygifty** [comment]
i am interested in fixing this issue

**Comment by oreoluwa212** [comment]
I'm interested in this fixing this issue
Assign to me

**Comment by jMkwendy45** [comment]
I am interested in fixing this, if it is not assigned yet.
