### ISSUE TITLE
make bold and add an email link

### ISSUE THREAD

**Issue by SCALagos** [SCALagos/SCALagos#13]
make everything on  line 42 bold 
 ```
42. FOR ENQUIRIES AND SPONSORSHIPS ON OUR PROGRAMS - CONTACT US VIA EMAIL

```
then make CONTACT US VIA EMAIL  a link that redirects to our email - shecodeafricalagos@gmail.com

**Comment by Coding-doves** [comment]
Hi SCA,
I am interested in fixing this issue. Please grant me the previlage

**Comment by AdaOkonkwoTech** [comment]
> make everything on line 42 bold
> 
> ```
> 42. FOR ENQUIRIES AND SPONSORSHIPS ON OUR PROGRAMS - CONTACT US VIA EMAIL
> ```
> 
> then make CONTACT US VIA EMAIL a link that redirects to our email - [shecodeafricalagos@gmail.com](mailto:shecodeafricalagos@gmail.com)

I am interested in fixing this bug
